# .github/release.yml

changelog:
  exclude:
    labels:
      - documentation
      - ignore
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
